# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cyclecare_pb2 as cyclecare__pb2


class CycleCareServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.uploadVideo = channel.stream_unary(
                '/cyclecare.CycleCareService/uploadVideo',
                request_serializer=cyclecare__pb2.VideoChunkResponse.SerializeToString,
                response_deserializer=cyclecare__pb2.StreamVideoRequest.FromString,
                )
        self.streamVideo = channel.unary_stream(
                '/cyclecare.CycleCareService/streamVideo',
                request_serializer=cyclecare__pb2.StreamVideoRequest.SerializeToString,
                response_deserializer=cyclecare__pb2.VideoChunkResponse.FromString,
                )


class CycleCareServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def uploadVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def streamVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CycleCareServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'uploadVideo': grpc.stream_unary_rpc_method_handler(
                    servicer.uploadVideo,
                    request_deserializer=cyclecare__pb2.VideoChunkResponse.FromString,
                    response_serializer=cyclecare__pb2.StreamVideoRequest.SerializeToString,
            ),
            'streamVideo': grpc.unary_stream_rpc_method_handler(
                    servicer.streamVideo,
                    request_deserializer=cyclecare__pb2.StreamVideoRequest.FromString,
                    response_serializer=cyclecare__pb2.VideoChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cyclecare.CycleCareService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CycleCareService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def uploadVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/cyclecare.CycleCareService/uploadVideo',
            cyclecare__pb2.VideoChunkResponse.SerializeToString,
            cyclecare__pb2.StreamVideoRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def streamVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cyclecare.CycleCareService/streamVideo',
            cyclecare__pb2.StreamVideoRequest.SerializeToString,
            cyclecare__pb2.VideoChunkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
