# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cyclecare.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63yclecare.proto\x12\tcyclecare\",\n\nVideoChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"-\n\x0cUploadStatus\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\" \n\x0cVideoRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t2\x94\x01\n\x10\x43ycleCareService\x12?\n\x0bUploadVideo\x12\x15.cyclecare.VideoChunk\x1a\x17.cyclecare.UploadStatus(\x01\x12?\n\x0bStreamVideo\x12\x17.cyclecare.VideoRequest\x1a\x15.cyclecare.VideoChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cyclecare_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEOCHUNK']._serialized_start=30
  _globals['_VIDEOCHUNK']._serialized_end=74
  _globals['_UPLOADSTATUS']._serialized_start=76
  _globals['_UPLOADSTATUS']._serialized_end=121
  _globals['_VIDEOREQUEST']._serialized_start=123
  _globals['_VIDEOREQUEST']._serialized_end=155
  _globals['_CYCLECARESERVICE']._serialized_start=158
  _globals['_CYCLECARESERVICE']._serialized_end=306
# @@protoc_insertion_point(module_scope)
